<?php
/**
 * AttributesApi
 * PHP version 5
 *
 * @category Class
 * @package  Dounasth\Ngsiv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Dounasth\Ngsiv2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Dounasth\Ngsiv2\ApiException;
use Dounasth\Ngsiv2\Configuration;
use Dounasth\Ngsiv2\HeaderSelector;
use Dounasth\Ngsiv2\ObjectSerializer;

/**
 * AttributesApi Class Doc Comment
 *
 * @category Class
 * @package  Dounasth\Ngsiv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AttributesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAttributeData
     *
     * Get attribute data
     *
     * @param  string $entity_id Id of the entity (required)
     * @param  string $attr_name Name of the attribute to be retrieved. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     * @param  string $metadata A list of metadata names to include in the response. See \&quot;Filtering out attributes and metadata\&quot; section for more detail. (optional)
     *
     * @throws \Dounasth\Ngsiv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Dounasth\Ngsiv2\Model\GetAttributeDataResponse
     */
    public function getAttributeData($entity_id, $attr_name, $type = null, $metadata = null)
    {
        list($response) = $this->getAttributeDataWithHttpInfo($entity_id, $attr_name, $type, $metadata);
        return $response;
    }

    /**
     * Operation getAttributeDataWithHttpInfo
     *
     * Get attribute data
     *
     * @param  string $entity_id Id of the entity (required)
     * @param  string $attr_name Name of the attribute to be retrieved. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     * @param  string $metadata A list of metadata names to include in the response. See \&quot;Filtering out attributes and metadata\&quot; section for more detail. (optional)
     *
     * @throws \Dounasth\Ngsiv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Dounasth\Ngsiv2\Model\GetAttributeDataResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAttributeDataWithHttpInfo($entity_id, $attr_name, $type = null, $metadata = null)
    {
        $returnType = '\Dounasth\Ngsiv2\Model\GetAttributeDataResponse';
        $request = $this->getAttributeDataRequest($entity_id, $attr_name, $type, $metadata);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dounasth\Ngsiv2\Model\GetAttributeDataResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAttributeDataAsync
     *
     * Get attribute data
     *
     * @param  string $entity_id Id of the entity (required)
     * @param  string $attr_name Name of the attribute to be retrieved. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     * @param  string $metadata A list of metadata names to include in the response. See \&quot;Filtering out attributes and metadata\&quot; section for more detail. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAttributeDataAsync($entity_id, $attr_name, $type = null, $metadata = null)
    {
        return $this->getAttributeDataAsyncWithHttpInfo($entity_id, $attr_name, $type, $metadata)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAttributeDataAsyncWithHttpInfo
     *
     * Get attribute data
     *
     * @param  string $entity_id Id of the entity (required)
     * @param  string $attr_name Name of the attribute to be retrieved. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     * @param  string $metadata A list of metadata names to include in the response. See \&quot;Filtering out attributes and metadata\&quot; section for more detail. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAttributeDataAsyncWithHttpInfo($entity_id, $attr_name, $type = null, $metadata = null)
    {
        $returnType = '\Dounasth\Ngsiv2\Model\GetAttributeDataResponse';
        $request = $this->getAttributeDataRequest($entity_id, $attr_name, $type, $metadata);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAttributeData'
     *
     * @param  string $entity_id Id of the entity (required)
     * @param  string $attr_name Name of the attribute to be retrieved. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     * @param  string $metadata A list of metadata names to include in the response. See \&quot;Filtering out attributes and metadata\&quot; section for more detail. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAttributeDataRequest($entity_id, $attr_name, $type = null, $metadata = null)
    {
        // verify the required parameter 'entity_id' is set
        if ($entity_id === null || (is_array($entity_id) && count($entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_id when calling getAttributeData'
            );
        }
        // verify the required parameter 'attr_name' is set
        if ($attr_name === null || (is_array($attr_name) && count($attr_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $attr_name when calling getAttributeData'
            );
        }

        $resourcePath = '/v2/entities/{entityId}/attrs/{attrName}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($type !== null) {
            $queryParams['type'] = ObjectSerializer::toQueryValue($type);
        }
        // query params
        if ($metadata !== null) {
            $queryParams['metadata'] = ObjectSerializer::toQueryValue($metadata);
        }

        // path params
        if ($entity_id !== null) {
            $resourcePath = str_replace(
                '{' . 'entityId' . '}',
                ObjectSerializer::toPathValue($entity_id),
                $resourcePath
            );
        }
        // path params
        if ($attr_name !== null) {
            $resourcePath = str_replace(
                '{' . 'attrName' . '}',
                ObjectSerializer::toPathValue($attr_name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
//            $headers,
//            $httpBody
        );
    }

    /**
     * Operation removeASingleAttribute
     *
     * Remove a Single Attribute
     *
     * @param  string $entity_id Id of the entity. (required)
     * @param  string $attr_name Attribute name. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \Dounasth\Ngsiv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function removeASingleAttribute($entity_id, $attr_name, $type = null)
    {
        $this->removeASingleAttributeWithHttpInfo($entity_id, $attr_name, $type);
    }

    /**
     * Operation removeASingleAttributeWithHttpInfo
     *
     * Remove a Single Attribute
     *
     * @param  string $entity_id Id of the entity. (required)
     * @param  string $attr_name Attribute name. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \Dounasth\Ngsiv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function removeASingleAttributeWithHttpInfo($entity_id, $attr_name, $type = null)
    {
        $returnType = '';
        $request = $this->removeASingleAttributeRequest($entity_id, $attr_name, $type);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation removeASingleAttributeAsync
     *
     * Remove a Single Attribute
     *
     * @param  string $entity_id Id of the entity. (required)
     * @param  string $attr_name Attribute name. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeASingleAttributeAsync($entity_id, $attr_name, $type = null)
    {
        return $this->removeASingleAttributeAsyncWithHttpInfo($entity_id, $attr_name, $type)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation removeASingleAttributeAsyncWithHttpInfo
     *
     * Remove a Single Attribute
     *
     * @param  string $entity_id Id of the entity. (required)
     * @param  string $attr_name Attribute name. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeASingleAttributeAsyncWithHttpInfo($entity_id, $attr_name, $type = null)
    {
        $returnType = '';
        $request = $this->removeASingleAttributeRequest($entity_id, $attr_name, $type);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'removeASingleAttribute'
     *
     * @param  string $entity_id Id of the entity. (required)
     * @param  string $attr_name Attribute name. (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function removeASingleAttributeRequest($entity_id, $attr_name, $type = null)
    {
        // verify the required parameter 'entity_id' is set
        if ($entity_id === null || (is_array($entity_id) && count($entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_id when calling removeASingleAttribute'
            );
        }
        // verify the required parameter 'attr_name' is set
        if ($attr_name === null || (is_array($attr_name) && count($attr_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $attr_name when calling removeASingleAttribute'
            );
        }

        $resourcePath = '/v2/entities/{entityId}/attrs/{attrName}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($type !== null) {
            $queryParams['type'] = ObjectSerializer::toQueryValue($type);
        }

        // path params
        if ($entity_id !== null) {
            $resourcePath = str_replace(
                '{' . 'entityId' . '}',
                ObjectSerializer::toPathValue($entity_id),
                $resourcePath
            );
        }
        // path params
        if ($attr_name !== null) {
            $resourcePath = str_replace(
                '{' . 'attrName' . '}',
                ObjectSerializer::toPathValue($attr_name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateAttributeData
     *
     * Update Attribute Data
     *
     * @param  string $entity_id Id of the entity to update (required)
     * @param  string $attr_name Attribute name (required)
     * @param  string $content_type  (required)
     * @param  \Dounasth\Ngsiv2\Model\UpdateAttributeDataRequest $body  (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \Dounasth\Ngsiv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateAttributeData($entity_id, $attr_name, $content_type, $body, $type = null)
    {
        $this->updateAttributeDataWithHttpInfo($entity_id, $attr_name, $content_type, $body, $type);
    }

    /**
     * Operation updateAttributeDataWithHttpInfo
     *
     * Update Attribute Data
     *
     * @param  string $entity_id Id of the entity to update (required)
     * @param  string $attr_name Attribute name (required)
     * @param  string $content_type  (required)
     * @param  \Dounasth\Ngsiv2\Model\UpdateAttributeDataRequest $body  (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \Dounasth\Ngsiv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateAttributeDataWithHttpInfo($entity_id, $attr_name, $content_type, $body, $type = null)
    {
        $returnType = '';
        $request = $this->updateAttributeDataRequest($entity_id, $attr_name, $content_type, $body, $type);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation updateAttributeDataAsync
     *
     * Update Attribute Data
     *
     * @param  string $entity_id Id of the entity to update (required)
     * @param  string $attr_name Attribute name (required)
     * @param  string $content_type  (required)
     * @param  \Dounasth\Ngsiv2\Model\UpdateAttributeDataRequest $body  (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAttributeDataAsync($entity_id, $attr_name, $content_type, $body, $type = null)
    {
        return $this->updateAttributeDataAsyncWithHttpInfo($entity_id, $attr_name, $content_type, $body, $type)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAttributeDataAsyncWithHttpInfo
     *
     * Update Attribute Data
     *
     * @param  string $entity_id Id of the entity to update (required)
     * @param  string $attr_name Attribute name (required)
     * @param  string $content_type  (required)
     * @param  \Dounasth\Ngsiv2\Model\UpdateAttributeDataRequest $body  (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAttributeDataAsyncWithHttpInfo($entity_id, $attr_name, $content_type, $body, $type = null)
    {
        $returnType = '';
        $request = $this->updateAttributeDataRequest($entity_id, $attr_name, $content_type, $body, $type);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateAttributeData'
     *
     * @param  string $entity_id Id of the entity to update (required)
     * @param  string $attr_name Attribute name (required)
     * @param  string $content_type  (required)
     * @param  \Dounasth\Ngsiv2\Model\UpdateAttributeDataRequest $body  (required)
     * @param  string $type Entity type, to avoid ambiguity in case there are several entities with the same entity id. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateAttributeDataRequest($entity_id, $attr_name, $content_type, $body, $type = null)
    {
        // verify the required parameter 'entity_id' is set
        if ($entity_id === null || (is_array($entity_id) && count($entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_id when calling updateAttributeData'
            );
        }
        // verify the required parameter 'attr_name' is set
        if ($attr_name === null || (is_array($attr_name) && count($attr_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $attr_name when calling updateAttributeData'
            );
        }
        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling updateAttributeData'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling updateAttributeData'
            );
        }

        $resourcePath = '/v2/entities/{entityId}/attrs/{attrName}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($type !== null) {
            $queryParams['type'] = ObjectSerializer::toQueryValue($type);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($entity_id !== null) {
            $resourcePath = str_replace(
                '{' . 'entityId' . '}',
                ObjectSerializer::toPathValue($entity_id),
                $resourcePath
            );
        }
        // path params
        if ($attr_name !== null) {
            $resourcePath = str_replace(
                '{' . 'attrName' . '}',
                ObjectSerializer::toPathValue($attr_name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
