<?php
/**
 * RetrieveApiResourcesResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RetrieveApiResourcesResponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RetrieveApiResourcesResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RetrieveApiResourcesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'entities_url' => 'string',
        'types_url' => 'string',
        'subscriptions_url' => 'string',
        'registrations_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'entities_url' => null,
        'types_url' => null,
        'subscriptions_url' => null,
        'registrations_url' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'entities_url' => 'entities_url',
        'types_url' => 'types_url',
        'subscriptions_url' => 'subscriptions_url',
        'registrations_url' => 'registrations_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'entities_url' => 'setEntitiesUrl',
        'types_url' => 'setTypesUrl',
        'subscriptions_url' => 'setSubscriptionsUrl',
        'registrations_url' => 'setRegistrationsUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'entities_url' => 'getEntitiesUrl',
        'types_url' => 'getTypesUrl',
        'subscriptions_url' => 'getSubscriptionsUrl',
        'registrations_url' => 'getRegistrationsUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['entities_url'] = isset($data['entities_url']) ? $data['entities_url'] : null;
        $this->container['types_url'] = isset($data['types_url']) ? $data['types_url'] : null;
        $this->container['subscriptions_url'] = isset($data['subscriptions_url']) ? $data['subscriptions_url'] : null;
        $this->container['registrations_url'] = isset($data['registrations_url']) ? $data['registrations_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['entities_url'] === null) {
            $invalidProperties[] = "'entities_url' can't be null";
        }
        if ($this->container['types_url'] === null) {
            $invalidProperties[] = "'types_url' can't be null";
        }
        if ($this->container['subscriptions_url'] === null) {
            $invalidProperties[] = "'subscriptions_url' can't be null";
        }
        if ($this->container['registrations_url'] === null) {
            $invalidProperties[] = "'registrations_url' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets entities_url
     *
     * @return string
     */
    public function getEntitiesUrl()
    {
        return $this->container['entities_url'];
    }

    /**
     * Sets entities_url
     *
     * @param string $entities_url URL which points to the entities resource
     *
     * @return $this
     */
    public function setEntitiesUrl($entities_url)
    {
        $this->container['entities_url'] = $entities_url;

        return $this;
    }

    /**
     * Gets types_url
     *
     * @return string
     */
    public function getTypesUrl()
    {
        return $this->container['types_url'];
    }

    /**
     * Sets types_url
     *
     * @param string $types_url URL which points to the types resource
     *
     * @return $this
     */
    public function setTypesUrl($types_url)
    {
        $this->container['types_url'] = $types_url;

        return $this;
    }

    /**
     * Gets subscriptions_url
     *
     * @return string
     */
    public function getSubscriptionsUrl()
    {
        return $this->container['subscriptions_url'];
    }

    /**
     * Sets subscriptions_url
     *
     * @param string $subscriptions_url URL which points to the subscriptions resource
     *
     * @return $this
     */
    public function setSubscriptionsUrl($subscriptions_url)
    {
        $this->container['subscriptions_url'] = $subscriptions_url;

        return $this;
    }

    /**
     * Gets registrations_url
     *
     * @return string
     */
    public function getRegistrationsUrl()
    {
        return $this->container['registrations_url'];
    }

    /**
     * Sets registrations_url
     *
     * @param string $registrations_url URL which points to the registrations resource
     *
     * @return $this
     */
    public function setRegistrationsUrl($registrations_url)
    {
        $this->container['registrations_url'] = $registrations_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


