<?php
/**
 * AttributeValueApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Dounasth\Ngsiv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Dounasth\Ngsiv2;

use \Dounasth\Ngsiv2\Configuration;
use \Dounasth\Ngsiv2\ApiException;
use \Dounasth\Ngsiv2\ObjectSerializer;

/**
 * AttributeValueApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dounasth\Ngsiv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AttributeValueApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAttributeValue
     *
     * Get Attribute Value.
     *
     */
    public function testGetAttributeValue()
    {
    }

    /**
     * Test case for updateAttributeValue
     *
     * Update Attribute Value.
     *
     */
    public function testUpdateAttributeValue()
    {
    }
}
