<?php
/**
 * EntitiesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EntitiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EntitiesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createEntity
     *
     * Create Entity.
     *
     */
    public function testCreateEntity()
    {
    }

    /**
     * Test case for listEntities
     *
     * List Entities.
     *
     */
    public function testListEntities()
    {
    }

    /**
     * Test case for removeEntity
     *
     * Remove Entity.
     *
     */
    public function testRemoveEntity()
    {
    }

    /**
     * Test case for replaceAllEntityAttributes
     *
     * Replace all entity attributes.
     *
     */
    public function testReplaceAllEntityAttributes()
    {
    }

    /**
     * Test case for retrieveEntity
     *
     * Retrieve Entity.
     *
     */
    public function testRetrieveEntity()
    {
    }

    /**
     * Test case for retrieveEntityAttributes
     *
     * Retrieve Entity Attributes.
     *
     */
    public function testRetrieveEntityAttributes()
    {
    }

    /**
     * Test case for updateExistingEntityAttributes
     *
     * Update Existing Entity Attributes.
     *
     */
    public function testUpdateExistingEntityAttributes()
    {
    }

    /**
     * Test case for updateOrAppendEntityAttributes
     *
     * Update or Append Entity Attributes.
     *
     */
    public function testUpdateOrAppendEntityAttributes()
    {
    }
}
