<?php
/**
 * SubscriptionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SubscriptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSubscription
     *
     * Create Subscription.
     *
     */
    public function testCreateSubscription()
    {
    }

    /**
     * Test case for deleteSubscription
     *
     * Delete subscription.
     *
     */
    public function testDeleteSubscription()
    {
    }

    /**
     * Test case for listSubscriptions
     *
     * List Subscriptions.
     *
     */
    public function testListSubscriptions()
    {
    }

    /**
     * Test case for retrieveSubscription
     *
     * Retrieve Subscription.
     *
     */
    public function testRetrieveSubscription()
    {
    }

    /**
     * Test case for updateSubscription
     *
     * Update Subscription.
     *
     */
    public function testUpdateSubscription()
    {
    }
}
